{% set name = "fps" %}
{% set version = "0.3.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 154755a541caf6dc94299bb398cb14ccc211963d57473a89079045275ce474d3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - fps = fps._cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - anyio
    - anyioutils >=0.7.0,<0.8.0
    - click >=8.1.8,<9
    - structlog
    - exceptiongroup
    - importlib_metadata
    - fastapi
    - anycorn >=0.18.1,<0.19.0

test:
  imports:
    - fps
    - fps.web
  commands:
    - pip check
    - fps --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jupyter-server/fps
  summary: Fast Pluggable System
  description: A system for creating modular, configurable, pluggable and concurrent applications
  dev_url: https://github.com/jupyter-server/fps
  doc_url: https://jupyter-server.github.io/fps
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - adriendelsalle
    - davidbrochart
