{% set name = "fps" %}
{% set version = "0.0.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 93d908c8b518b14879f1128f467834311ad1ae546ca6e49b47d72d0aa00f22f6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - fastapi
    - pluggy >=1.0.0,<2.0.0
    - toml
    - typer
    - rich

test:
  imports:
    - fps

about:
  home: https://github.com/jupyter-server/fps
  summary: A fast plugin server
  description: A fast plugin server based on FastAPI and pluggy, providing a composable way to build a web-server
  keywords: asgi, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/fps
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - adriendelsalle
    - davidbrochart
