{% set name = "fps" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0fa0f407cb23f0dc4623a68567bc106b82789890627ee84077efe027e0f86548

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - fps = fps._cli:main

requirements:
  host:
    - python >=3.9
    - pip
    - hatchling
  run:
    - python >=3.9
    - anyio
    - anyioutils >=0.4.9
    - click >=8.1.8,<9
    - structlog
    - exceptiongroup
    - importlib_metadata
    - fastapi
    - anycorn

test:
  imports:
    - fps
    - fps.web.FastAPIModule
  commands:
    - pip check
    - fps --help
  requires:
    - pip
    - python >=3.9

about:
  home: https://github.com/jupyter-server/fps
  summary: Fast Pluggable System
  description: A system for creating modular, configurable, pluggable and concurrent applications
  dev_url: https://github.com/jupyter-server/fps
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - adriendelsalle
    - davidbrochart
