{% set name = "fps" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-server/fps/archive/{{ version }}.tar.gz
  sha256: 13467be3c3624ebc338a869c50027019e8ace41ec9ea2e1f7f6b5dec77f7f784

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fastapi
    - pluggy >=1.0.0,<2.0.0
    - toml

test:
  imports:
    - fps

about:
  home: https://github.com/jupyter-server/fps
  summary: A fast plugins server
  description: A fast plugin server based on fastAPI and pluggy, providing a composable way to build a web-server
  keywords: asgi, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/fps
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - adriendelsalle
