{% set name = "fps" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-server/fps/archive/fps-{{ version }}.tar.gz
  sha256: b1624df4c9c0923ecddaff3679bb45e407abdeee68076ead47b065921adcc7bc

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fastapi
    - pluggy >=1.0.0,<2.0.0
    - toml
    - click

test:
  imports:
    - fps

about:
  home: https://github.com/jupyter-server/fps
  summary: A fast plugins server
  description: A fast plugin server based on fastAPI and pluggy, providing a composable way to build a web-server
  keywords: asgi, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/fps
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - adriendelsalle
